### ISSUE TITLE
No response for search

### ISSUE THREAD

**Issue by notjedi** [pawamoy/TPB#11]
```python
t = TPB('https://pirateproxy.tube/')

for torrent in t.search('interstellar'):
    print(torrent.info)
```
this is my code and the search object doesn't return anything i guess because it is not printing anything. am i going wrong somewhere or is the fault on your side?

piratebay is actually blocked in my country but the url above does work when i open it on my web browser.

**Comment by luiscorujo** [comment]
I have the same problem

**Comment by bassettmason** [comment]
any one solve this yet?

**Comment by danon** [comment]
@notjedi Did you find a solution?

I'm trying to find items in thepiratebay using custom criteria.
