### ISSUE TITLE
ImportError: cannot import name 'TPB' from 'tpb' 

### ISSUE THREAD

**Issue by liniuta** [pawamoy/TPB#8]
This is my code:
`from tpb import TPB`
`from tpb import CATEGORIES, ORDERS`

`t = TPB('https://boatairproxy.org/')`
`search = t.search('public domain', category=CATEGORIES.VIDEO.MOVIES)`

I get the error in the title when i run..

**Comment by jacksonv1lle** [comment]
I too get this error

**Comment by jacksonv1lle** [comment]
I have resolved it. It was because I was using the library within a file named 'tpb.py'
